name: Deploy

on:
  workflow_dispatch:
    inputs:
      grid:
        description: "grid to deploy"
        required: true
        default: "qa"
        type: choice
        options:
          - qa-v4
          - testing-v4
          - production-v4
      version:
        description: "version to release"
        required: true
        type: string
jobs:
  link-release:
    name: linking
    runs-on: ubuntu-latest
    steps:
      - name: Symlink flist (development)
        uses: threefoldtech/publish-flist@master
        with:
          token: ${{ secrets.HUB_JWT }}
          baseurl: "https://v4.hub.grid.tf"
          backend: "v4.hub.grid.tf:9941"
          action: crosslink
          user: tf-zos
          name: ${{ github.event.inputs.grid }}
          target: tf-autobuilder/zos:${{ github.event.inputs.version }}.flist
